#---Profile Properties---
#Available profiles: local, remote
#Set remote when deploy to server
spring:
  profiles:
    active: local
  rabbitmq:
    dynamic: true
    cache:
      connection:
        mode: channel
#    listener:
#      simple:
#        auto-startup: false
##---Loggin Properties---
logging:
  level:
    com.bobbbaich: DEBUG
server:
  8080
queue:
  snapshotCandles: snapshotCandle${server}
  updateCandles: updateCandle${server}
  ticker: ticker${server}